name: 'Gradle build'
description: 'Run gradle test'
runs:
  using: "composite"
  steps:
    - name: 'Set up latest Oracle JDK 17'
      uses: oracle-actions/setup-java@v1
      with:
        website: oracle.com
        release: 17
    - name: Make gradlew executable
      shell: bash
      run: chmod +x ./gradlew
    - name: Run the Gradle test task
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test