name: 'Gradle build'
description: 'Run gradle test'
runs:
  using: "composite"
  steps:
    - name: Make gradlew executable
      shell: bash
      run: chmod +x ./gradlew
    - name: Run the Gradle test task
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
